### ISSUE TITLE
Add the example please?

### ISSUE THREAD

**Issue by gerardsimons** [WilliBobadilla/custom_battery_indicator#1]
Hey! Nice work on this, exactly what I needed. Still trying to figure out how to use it exactly though. An example would really help (the one from the screenshot?) and maybe a bit more documentation.

**Comment by WilliBobadilla** [comment]
hello! yes, let me take a time to do that! what state manager are you using?

**Comment by WilliBobadilla** [comment]
let me write a example without framework, because in the test I am using GetX

**Comment by WilliBobadilla** [comment]
check this new repo forked from the original source: https://github.com/WilliBobadilla/battery_indicator/tree/dev_custom_battery_level  <br>
You can check in the examples forlders the use of the widget, I will make a PR to the original repo from https://github.com/debuggerx01/battery_indicator

**Comment by gerardsimons** [comment]
Thank you, I'll take a look!

**Comment by WilliBobadilla** [comment]
you are welcome! :+1:
